### ISSUE TITLE
Are there plans to support the grpc protocol or http protocol?

### ISSUE THREAD

**Issue by qingfeng** [SirRender00/texasholdem#118]
thanks

**Comment by SirRender00** [comment]
Sorry, not quite sure what you mean. Do you mean ability to host a web server?

**Comment by qingfeng** [comment]
> Sorry, not quite sure what you mean. Do you mean ability to host a web server & client?

Yes, are there plans to support web server & client? thanks

**Comment by SirRender00** [comment]
Yeah, we can definitely have a discussion later down the line about that. If this work would be done, it'd be around the same time or soon after this https://github.com/SirRender00/texasholdem/issues/66.
