### ISSUE TITLE
Display action information in the text GUI

### ISSUE THREAD

**Issue by SirRender00** [SirRender00/texasholdem#131]
Should display basic action information in the text gui such as 

- chips to call
- Min raise
- Available actions

**Comment by hlmaestretti** [comment]
Assign me please.

I'm assuming you'd what the action information to go under the text "Player X's turn"

Should look something like this:

Board state: pre-flop, player 0 (button) has 0 chips in, player 6 raised bid from 5 to 10
"
Player 0's turn:
Chips to call: 10
Min raise: 15
Available Actions: Fold, Call, Raise 15
"

**Comment by SirRender00** [comment]
Yeah! That last line right above the input box would be good, something like:

`Available Actions: Fold, Call 10, Raise to 15`

**Comment by SirRender00** [comment]
This issue can depend on this https://github.com/SirRender00/texasholdem/issues/132 to be able to pull in these moves
