### ISSUE TITLE
Include iterator over all valid moves

### ISSUE THREAD

**Issue by SirRender00** [SirRender00/texasholdem#132]
Should be able to do things like

- `(ActionType.RAISE, 50) in game.get_all_available_moves()`
- `ActionType.CALL in game.get_all_available_moves()`
- `(ActionType.CHECK, None) in game.get_all_available_moves()`
- `(ActionType.CHECK, 50) in game.get_all_available_moves() # True`
- `for action, val in game.get_all_available_moves(): print(action, val)`

All `in` operations should be completed in `O(1)` time in the number of possible moves and chips.

**Comment by gustavomfb** [comment]
could you asign this one to me?

**Comment by SirRender00** [comment]
@gustavomfb Hey! Glad to have you interested in contributing to the package. 

What were your thoughts on implementing this one?
