### ISSUE TITLE
ValueError: Betting round is over at this point, can only CALL or FOLD.

### ISSUE THREAD

**Issue by LucasColas** [SirRender00/texasholdem#186]
Hello,
Sometimes I get this error : 
`ValueError: Betting round is over at this point, can only CALL or FOLD.`
I would like to know when it happens. Because in no-limit hold'em, players have the option to raise at any point in the hand (as long as they have chips remaining).

**Comment by SirRender00** [comment]
Hey! Can you provide a hand history for when you get this? 

You might be running into WSOP Rule 96 https://github.com/SirRender00/texasholdem/pull/56

**Comment by SirRender00** [comment]
You can also check if the raise option is available due to this rule via the `game.raise_option: bool` attribute
