### ISSUE TITLE
Get the players that are still in a tournament

### ISSUE THREAD

**Issue by LucasColas** [SirRender00/texasholdem#192]
Hello,
is there a way to get the players that are still in a tournament ?

**Comment by SirRender00** [comment]
Hey! I believe this might be what you're looking for? https://texasholdem.readthedocs.io/en/stable/game_information.html#players. Players still in the tournament (i.e. game) would have states: IN, OUT, TO_CALL, ALL_IN. In other words, not SKIP state.

**Comment by LucasColas** [comment]
I'm not sure to know how I can get players who have states IN, OUT, TO_CALL, ALL_IN

**Comment by SirRender00** [comment]
Something like

```
game.player_iter(filter_states=(PlayerState.SKIP,))
```

should work

**Comment by LucasColas** [comment]
Ok thank you.
