### ISSUE TITLE
Gui not working

### ISSUE THREAD

**Issue by LucasColas** [SirRender00/texasholdem#264]
Hello, 
I recently tried to run a python script with gui but it's not working. I have no gui. And I have no error. I run my script from a powershell in windows.
Here's the code : 
```python
from texasholdem.game.game import TexasHoldEm
from texasholdem.gui.text_gui import TextGUI

game = TexasHoldEm(buyin=500, big_blind=5, small_blind=2, max_players=6)
gui = TextGUI(game=game)

while game.is_game_running():
    game.start_hand()

    while game.is_hand_running():
        gui.run_step()

    path = game.export_history('./pgns')     # save history
    gui.replay_history(path) 
```

My python version : 3.12.1
My texasholdem version : 0.10.0. I can't install the 0.11.0 version. pip doesn't find this version.

**Comment by LucasColas** [comment]
I switched to python 3.9 and now it works. It seems it's because of python 3.12. So I will wait another version of the library.

**Comment by SirRender00** [comment]
Looks like the deployment failed pending a tag protection I set up. This is good now 👍

**Comment by LucasColas** [comment]
Alright !
